export const options = {
  cleanupAttrs: {
    title: "cleanupAttrs",
    description: "cleanup attributes from newlines, trailing, and repeating spaces",
    detail: "https://github.com/svg/svgo/blob/main/plugins/cleanupAttrs.js",
    default: true,
  },
  mergeStyles: {
    title: "mergeStyles",
    description: "merge multiple style elements into one",
    detail: "https://github.com/svg/svgo/blob/main/plugins/mergeStyles.js",
    default: true,
  },
  inlineStyles: {
    title: "inlineStyles",
    description: "move and merge styles from <style> elements to element style attributes",
    detail: "https://github.com/svg/svgo/blob/main/plugins/inlineStyles.js",
    default: true,
  },
  removeDoctype: {
    title: "removeDoctype",
    description: "remove doctype declaration",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeDoctype.js",
    default: true,
  },
  removeXMLProcInst: {
    title: "removeXMLProcInst",
    description: "remove XML processing instructions",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeXMLProcInst.js",
    default: true,
  },
  removeComments: {
    title: "removeComments",
    description: "remove comments",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeComments.js",
    default: true,
  },
  removeMetadata: {
    title: "removeMetadata",
    description: "remove <metadata>",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeMetadata.js",
    default: true,
  },
  removeTitle: {
    title: "removeTitle",
    description: "remove <title>",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeTitle.js",
    default: true,
  },
  removeDesc: {
    title: "removeDesc",
    description: "remove <desc>",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeDesc.js",
    default: true,
  },
  removeUselessDefs: {
    title: "removeUselessDefs",
    description: "remove elements of <defs> without id",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeUselessDefs.js",
    default: true,
  },
  removeXMLNS: {
    title: "removeXMLNS",
    description: "removes the xmlns attribute (for inline SVG)",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeXMLNS.js",
    default: false,
  },
  removeEditorsNSData: {
    title: "removeEditorsNSData",
    description: "remove editors namespaces, elements, and attributes",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeEditorsNSData.js",
    default: true,
  },
  removeEmptyAttrs: {
    title: "removeEmptyAttrs",
    description: "remove empty attributes",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeEmptyAttrs.js",
    default: true,
  },
  removeHiddenElems: {
    title: "removeHiddenElems",
    description: "remove hidden elements",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeHiddenElems.js",
    default: true,
  },
  removeEmptyText: {
    title: "removeEmptyText",
    description: "remove empty Text elements",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeEmptyText.js",
    default: true,
  },
  removeEmptyContainers: {
    title: "removeEmptyContainers",
    description: "remove empty Container elements",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeEmptyContainers.js",
    default: true,
  },
  removeViewBox: {
    title: "removeViewBox",
    description: "remove viewBox attribute when possible",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeViewBox.js",
    default: true,
  },
  cleanupEnableBackground: {
    title: "cleanupEnableBackground",
    description: "remove or cleanup enable-background attribute when possible",
    detail: "https://github.com/svg/svgo/blob/main/plugins/cleanupEnableBackground.js",
    default: true,
  },
  minifyStyles: {
    title: "minifyStyles",
    description: "minify <style> elements content with CSSO",
    detail: "https://github.com/svg/svgo/blob/main/plugins/minifyStyles.js",
    default: true,
  },
  convertStyleToAttrs: {
    title: "convertStyleToAttrs",
    description: "convert styles into attributes",
    detail: "https://github.com/svg/svgo/blob/main/plugins/convertStyleToAttrs.js",
    default: false,
  },
  convertColors: {
    title: "convertColors",
    description: "convert colors (from rgb() to #rrggbb, from #rrggbb to #rgb)",
    detail: "https://github.com/svg/svgo/blob/main/plugins/convertColors.js",
    default: true,
  },
  convertPathData: {
    title: "convertPathData",
    description:
      "convert Path data to relative or absolute (whichever is shorter), convert one segment to another, trim useless delimiters, smart rounding, and much more",
    detail: "https://github.com/svg/svgo/blob/main/plugins/convertPathData.js",
    default: true,
  },
  convertTransform: {
    title: "convertTransform",
    description: "collapse multiple transforms into one, convert matrices to the short aliases, and much more",
    detail: "https://github.com/svg/svgo/blob/main/plugins/convertTransform.js",
    default: true,
  },
  removeUnknownsAndDefaults: {
    title: "removeUnknownsAndDefaults",
    description: "remove unknown elements content and attributes, remove attributes with default values",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeUnknownsAndDefaults.js",
    default: true,
  },
  removeNonInheritableGroupAttrs: {
    title: "removeNonInheritableGroupAttrs",
    description: "remove non-inheritable group's 'presentation' attributes",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeNonInheritableGroupAttrs.js",
    default: true,
  },
  removeUselessStrokeAndFill: {
    title: "removeUselessStrokeAndFill",
    description: "remove useless stroke and fill attributes",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeUselessStrokeAndFill.js",
    default: true,
  },
  removeUnusedNS: {
    title: "removeUnusedNS",
    description: "remove unused namespaces declaration",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeUnusedNS.js",
    default: true,
  },
  prefixIds: {
    title: "prefixIds",
    description: "prefix IDs and classes with the SVG filename or an arbitrary string",
    detail: "https://github.com/svg/svgo/blob/main/plugins/prefixIds.js",
    default: false,
  },
  cleanupIDs: {
    title: "cleanupIDs",
    description: "remove unused and minify used IDs",
    detail: "https://github.com/svg/svgo/blob/main/plugins/cleanupIDs.js",
    default: true,
  },
  cleanupNumericValues: {
    title: "cleanupNumericValues",
    description: "round numeric values to the fixed precision, remove default px units",
    detail: "https://github.com/svg/svgo/blob/main/plugins/cleanupNumericValues.js",
    default: true,
  },
  cleanupListOfValues: {
    title: "cleanupListOfValues",
    description: "round numeric values in attributes that take a list of numbers (like viewBox or enable-background)",
    detail: "https://github.com/svg/svgo/blob/main/plugins/cleanupListOfValues.js",
    default: false,
  },
  moveElemsAttrsToGroup: {
    title: "moveElemsAttrsToGroup",
    description: "move elements' attributes to their enclosing group",
    detail: "https://github.com/svg/svgo/blob/main/plugins/moveElemsAttrsToGroup.js",
    default: true,
  },
  moveGroupAttrsToElems: {
    title: "moveGroupAttrsToElems",
    description: "move some group attributes to the contained elements",
    detail: "https://github.com/svg/svgo/blob/main/plugins/moveGroupAttrsToElems.js",
    default: true,
  },
  collapseGroups: {
    title: "collapseGroups",
    description: "collapse useless groups",
    detail: "https://github.com/svg/svgo/blob/main/plugins/collapseGroups.js",
    default: true,
  },
  removeRasterImages: {
    title: "removeRasterImages",
    description: "remove raster images",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeRasterImages.js",
    default: false,
  },
  mergePaths: {
    title: "mergePaths",
    description: "merge multiple Paths into one",
    detail: "https://github.com/svg/svgo/blob/main/plugins/mergePaths.js",
    default: true,
  },
  convertShapeToPath: {
    title: "convertShapeToPath",
    description: "convert some basic shapes to <path>",
    detail: "https://github.com/svg/svgo/blob/main/plugins/convertShapeToPath.js",
    default: true,
  },
  convertEllipseToCircle: {
    title: "convertEllipseToCircle",
    description: "convert non-eccentric <ellipse> to <circle>",
    detail: "https://github.com/svg/svgo/blob/main/plugins/convertEllipseToCircle.js",
    default: true,
  },
  sortAttrs: {
    title: "sortAttrs",
    description: "sort element attributes for epic readability",
    detail: "https://github.com/svg/svgo/blob/main/plugins/sortAttrs.js",
    default: false,
  },
  sortDefsChildren: {
    title: "sortDefsChildren",
    description: "sort children of <defs> in order to improve compression",
    detail: "https://github.com/svg/svgo/blob/main/plugins/sortDefsChildren.js",
    default: true,
  },
  removeDimensions: {
    title: "removeDimensions",
    description: "remove width/height and add viewBox if it's missing (opposite to removeViewBox, disable it first)",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeDimensions.js",
    default: false,
  },
  removeAttrs: {
    title: "removeAttrs",
    description: "remove empty Container elements",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeEmptyContainers.js",
    default: false,
  },
  removeAttributesBySelector: {
    title: "removeAttributesBySelector",
    description: "removes attributes of elements that match a CSS selector",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeAttributesBySelector.js",
    default: false,
  },
  removeElementsByAttr: {
    title: "removeElementsByAttr",
    description: "remove arbitrary elements by ID or className",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeElementsByAttr.js",
    default: false,
  },
  addClassesToSVGElement: {
    title: "addClassesToSVGElement",
    description: "add classnames to an outer <svg> element",
    detail: "https://github.com/svg/svgo/blob/main/plugins/addClassesToSVGElement.js",
    default: false,
  },
  addAttributesToSVGElement: {
    title: "addAttributesToSVGElement",
    description: "adds attributes to an outer <svg> element",
    detail: "https://github.com/svg/svgo/blob/main/plugins/addAttributesToSVGElement.js",
    default: false,
  },
  removeOffCanvasPaths: {
    title: "removeOffCanvasPaths",
    description: "removes elements that are drawn outside of the viewbox",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeOffCanvasPaths.js",
    default: false,
  },
  removeStyleElement: {
    title: "removeStyleElement",
    description: "remove <style> elements",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeStyleElement.js",
    default: false,
  },
  removeScriptElement: {
    title: "removeScriptElement",
    description: "remove <script> elements",
    detail: "https://github.com/svg/svgo/blob/main/plugins/removeScriptElement.js",
    default: false,
  },
  reusePaths: {
    title: "reusePaths",
    description: "Find duplicated elements and replace them with links",
    detail: "https://github.com/svg/svgo/blob/main/plugins/reusePaths.js",
    default: false,
  },
};
